public enum ClientPacketId
{
    None = 0,
    Create,
    Delete,
    Login,
    Logout,
    GameClose,
    HeroDataRequest,
    SkillDataRequest,
    ItemDataRequest,
    UnitDataRequest,
    BuildingDataRequest,
    UpgradeDataRequest,
    ResourceDataRequest,
    StateDataRequest,
    Build,
    BuildCancel,
    BuildDataRequest,
    BuildComplete,
    UnitCreate,
    UnitCreateDataRequest,
    UnitCreateComplete,
    MyPositionDataRequest,
    PlaceDataRequest,
    EnemyUnitNumRequest,
    Attack,
    EnemyUnitDataRequest,
}

public enum ServerPacketId
{
    None = 0,
    CreateResult,
    DeleteResult,
    LoginResult,
    HeroData,
    SkillData,
    ItemData,
    UnitData,
    BuildingData,
    UpgradeData,
    ResourceData,
    StateData,
    BuildData,
    UnitCreateData,
    MyPositionData,
    PlaceData,
    EnemyUnitNumData,
    EnemyUnitData,
}